// Built-in categories. Each item is "emoji name" or just "name"; items without
// an emoji get a colored letter badge instead. Adding a category is just
// adding an entry here.
window.CATEGORIES = [
  {
    id: 'fast-food',
    name: 'Fast Food',
    emoji: '🍔',
    items: [
      '🍕 Pizza', '🍔 Burger', '🌮 Tacos', '🌭 Hot Dog', '🍟 Fries', '🍗 Fried Chicken',
      '🌯 Burrito', '🥪 Sub Sandwich', '🍝 Spaghetti', '🍜 Ramen', '🍣 Sushi', '🥙 Kebab',
      '🥟 Dumplings', '🍤 Fried Shrimp', '🧆 Falafel', '🥓 Bacon', '🥞 Pancakes', '🧇 Waffles',
      '🌶️ Nachos', '🧀 Mac & Cheese', '🥐 Croissant', '🥯 Bagel', '🍱 Bento Box', '🍛 Curry',
      '🥗 Salad', '🍦 Soft Serve', '🍩 Donut', '🥤 Milkshake', '🧅 Onion Rings', '🐔 Chicken Nuggets',
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🐾',
    items: [
      '🐶 Dog', '🐱 Cat', '🦁 Lion', '🐯 Tiger', '🐻 Bear', '🐼 Panda', '🐨 Koala', '🦊 Fox',
      '🐺 Wolf', '🦝 Raccoon', '🐸 Frog', '🐧 Penguin', '🦉 Owl', '🦅 Eagle', '🦈 Shark',
      '🐬 Dolphin', '🐙 Octopus', '🐢 Turtle', '🦒 Giraffe', '🐘 Elephant', '🦓 Zebra',
      '🦘 Kangaroo', '🦥 Sloth', '🦦 Otter', '🐿️ Squirrel', '🦔 Hedgehog', '🐍 Snake',
      '🦖 T-Rex', '🐝 Bee', '🦋 Butterfly', '🐴 Horse', '🐮 Cow', '🐷 Pig', '🐰 Rabbit',
      '🦩 Flamingo', '🐊 Crocodile', '🦭 Seal', '🐋 Whale', '🦙 Llama', '🦫 Beaver',
    ],
  },
  {
    id: 'minecraft-blocks',
    name: 'Minecraft Blocks',
    emoji: '🧱',
    items: [
      'Grass Block', 'Dirt', 'Stone', 'Cobblestone', 'Oak Planks', 'Oak Log', 'Glass', 'Sand',
      'Gravel', 'Obsidian', 'Bedrock', 'Diamond Ore', 'Iron Ore', 'Gold Ore', 'Coal Ore',
      'Redstone Ore', 'Emerald Ore', 'Ancient Debris', 'TNT', 'Crafting Table', 'Furnace',
      'Chest', 'Bookshelf', 'Enchanting Table', 'Beacon', 'Netherrack', 'Glowstone',
      'Sea Lantern', 'End Stone', 'Deepslate', 'Amethyst Block', 'Honey Block', 'Slime Block',
      'Sculk Sensor', 'Prismarine', 'Quartz Block', 'Terracotta', 'Wool', 'Pumpkin',
      'Jack o\'Lantern', 'Hay Bale', 'Ice', 'Packed Ice', 'Magma Block', 'Soul Sand',
      'Crying Obsidian', 'Moss Block', 'Mud Bricks', 'Cherry Planks', 'Copper Block',
    ],
  },
  {
    id: 'minecraft-items',
    name: 'Minecraft Items',
    emoji: '⛏️',
    items: [
      'Diamond Sword', 'Netherite Sword', 'Diamond Pickaxe', 'Bow', 'Crossbow', 'Trident',
      'Mace', 'Shield', 'Elytra', 'Totem of Undying', 'Ender Pearl', 'Eye of Ender',
      'Fishing Rod', 'Flint and Steel', 'Water Bucket', 'Lava Bucket', 'Golden Apple',
      'Enchanted Golden Apple', 'Cooked Steak', 'Bread', 'Cake', 'Cookie', 'Pumpkin Pie',
      'Suspicious Stew', 'Firework Rocket', 'Name Tag', 'Saddle', 'Lead', 'Compass',
      'Clock', 'Map', 'Spyglass', 'Book and Quill', 'Nether Star', 'Heart of the Sea',
      'Music Disc', 'Potion of Healing', 'Splash Potion', 'Experience Bottle', 'Shears',
      'Bone Meal', 'Slimeball', 'Blaze Rod', 'Ender Chest', 'Shulker Box', 'Minecart',
      'Boat', 'Armor Stand', 'Snowball', 'Egg',
    ],
  },
  {
    id: 'video-games',
    name: 'Video Games',
    emoji: '🎮',
    items: [
      'Minecraft', 'Fortnite', 'Roblox', 'The Legend of Zelda: Breath of the Wild',
      'Super Mario Odyssey', 'Mario Kart 8', 'Super Smash Bros. Ultimate', 'Animal Crossing: New Horizons',
      'Pokémon Scarlet & Violet', 'Grand Theft Auto V', 'Red Dead Redemption 2', 'The Witcher 3',
      'Elden Ring', 'Dark Souls', 'Hollow Knight', 'Celeste', 'Stardew Valley', 'Terraria',
      'Among Us', 'Fall Guys', 'Rocket League', 'Overwatch 2', 'Valorant', 'Counter-Strike 2',
      'League of Legends', 'Apex Legends', 'Call of Duty: Warzone', 'Halo 3', 'Portal 2',
      'Half-Life 2', 'The Last of Us', 'God of War', 'Spider-Man', 'Skyrim', 'Fallout 4',
      'Tetris', 'Pac-Man', 'Undertale', 'Hades', 'Baldur\'s Gate 3', 'Cyberpunk 2077',
      'Genshin Impact', 'Subnautica', 'Geometry Dash', 'Cuphead', 'Sonic Mania',
      'Splatoon 3', 'Tears of the Kingdom', 'Balatro', 'Lethal Company',
    ],
  },
  {
    id: 'movies',
    name: 'Movies',
    emoji: '🎬',
    items: [
      'The Lion King', 'Toy Story', 'Finding Nemo', 'Shrek', 'Frozen', 'Up', 'Inside Out',
      'Spider-Man: Into the Spider-Verse', 'The Dark Knight', 'Avengers: Endgame', 'Iron Man',
      'Star Wars: A New Hope', 'The Empire Strikes Back', 'Jurassic Park', 'Back to the Future',
      'E.T.', 'Jaws', 'Titanic', 'Avatar', 'The Matrix', 'Inception', 'Interstellar',
      'The Lord of the Rings', 'Harry Potter and the Sorcerer\'s Stone', 'Spirited Away',
      'My Neighbor Totoro', 'Coco', 'Ratatouille', 'WALL-E', 'The Incredibles', 'Monsters, Inc.',
      'Pirates of the Caribbean', 'Home Alone', 'Ghostbusters', 'Indiana Jones', 'Top Gun: Maverick',
      'The Super Mario Bros. Movie', 'Barbie', 'Oppenheimer', 'Dune', 'Everything Everywhere All at Once',
      'The Godfather', 'Pulp Fiction', 'Forrest Gump', 'The Shawshank Redemption', 'A Minecraft Movie',
    ],
  },
  {
    id: 'anime-characters',
    name: 'Anime Characters',
    emoji: '🍥',
    items: [
      'Goku', 'Vegeta', 'Naruto', 'Sasuke', 'Kakashi', 'Luffy', 'Zoro', 'Nami', 'Sanji',
      'Ichigo', 'Eren Yeager', 'Levi Ackerman', 'Mikasa', 'Light Yagami', 'L', 'Edward Elric',
      'Saitama', 'Genos', 'Tanjiro', 'Nezuko', 'Zenitsu', 'Gojo Satoru', 'Yuji Itadori',
      'Sukuna', 'Deku', 'Bakugo', 'All Might', 'Todoroki', 'Gon', 'Killua', 'Spike Spiegel',
      'Sailor Moon', 'Pikachu', 'Ash Ketchum', 'Anya Forger', 'Loid Forger', 'Yor Forger',
      'Denji', 'Power', 'Makima', 'Frieren', 'Lelouch', 'Senku', 'Mob', 'Kirito',
      'Rem', 'Asuna', 'Totoro', 'Jotaro Kujo', 'Dio Brando',
    ],
  },
  {
    id: 'songs',
    name: 'Songs',
    emoji: '🎵',
    items: [
      'Bohemian Rhapsody — Queen', 'Billie Jean — Michael Jackson', 'Smells Like Teen Spirit — Nirvana',
      'Hey Jude — The Beatles', 'Mr. Brightside — The Killers', 'Blinding Lights — The Weeknd',
      'Shape of You — Ed Sheeran', 'Bad Guy — Billie Eilish', 'Uptown Funk — Bruno Mars',
      'Rolling in the Deep — Adele', 'Shake It Off — Taylor Swift', 'Anti-Hero — Taylor Swift',
      'Levitating — Dua Lipa', 'drivers license — Olivia Rodrigo', 'Old Town Road — Lil Nas X',
      'Happy — Pharrell Williams', 'Believer — Imagine Dragons', 'Thriller — Michael Jackson',
      'Don\'t Stop Believin\' — Journey', 'Sweet Child O\' Mine — Guns N\' Roses',
      'Wonderwall — Oasis', 'Take On Me — a-ha', 'Africa — Toto', 'Never Gonna Give You Up — Rick Astley',
      'Stayin\' Alive — Bee Gees', 'Dancing Queen — ABBA', 'Lose Yourself — Eminem',
      'HUMBLE. — Kendrick Lamar', 'Sicko Mode — Travis Scott', 'Crazy in Love — Beyoncé',
      'Toxic — Britney Spears', 'Seven Nation Army — The White Stripes', 'Radioactive — Imagine Dragons',
      'Espresso — Sabrina Carpenter', 'Flowers — Miley Cyrus', 'As It Was — Harry Styles',
      'Gangnam Style — PSY', 'Dynamite — BTS', 'Despacito — Luis Fonsi', 'Viva La Vida — Coldplay',
    ],
  },
  {
    id: 'countries',
    name: 'Countries',
    emoji: '🌍',
    items: [
      '🇺🇸 United States', '🇨🇦 Canada', '🇲🇽 Mexico', '🇧🇷 Brazil', '🇦🇷 Argentina', '🇬🇧 United Kingdom',
      '🇮🇪 Ireland', '🇫🇷 France', '🇩🇪 Germany', '🇮🇹 Italy', '🇪🇸 Spain', '🇵🇹 Portugal',
      '🇳🇱 Netherlands', '🇸🇪 Sweden', '🇳🇴 Norway', '🇫🇮 Finland', '🇩🇰 Denmark', '🇮🇸 Iceland',
      '🇨🇭 Switzerland', '🇬🇷 Greece', '🇵🇱 Poland', '🇹🇷 Turkey', '🇪🇬 Egypt', '🇲🇦 Morocco',
      '🇳🇬 Nigeria', '🇰🇪 Kenya', '🇿🇦 South Africa', '🇮🇳 India', '🇨🇳 China', '🇯🇵 Japan',
      '🇰🇷 South Korea', '🇹🇭 Thailand', '🇻🇳 Vietnam', '🇮🇩 Indonesia', '🇵🇭 Philippines',
      '🇦🇺 Australia', '🇳🇿 New Zealand', '🇨🇱 Chile', '🇵🇪 Peru', '🇨🇴 Colombia',
    ],
  },
  {
    id: 'pokemon',
    name: 'Pokémon',
    emoji: '⚡',
    items: [
      'Pikachu', 'Bulbasaur', 'Charmander', 'Squirtle', 'Charizard', 'Blastoise', 'Venusaur',
      'Mewtwo', 'Mew', 'Eevee', 'Snorlax', 'Gengar', 'Jigglypuff', 'Psyduck', 'Magikarp',
      'Gyarados', 'Dragonite', 'Lapras', 'Ditto', 'Lucario', 'Greninja', 'Rayquaza', 'Lugia',
      'Ho-Oh', 'Umbreon', 'Sylveon', 'Gardevoir', 'Garchomp', 'Tyranitar', 'Mimikyu',
      'Togepi', 'Cubone', 'Arcanine', 'Vaporeon', 'Jolteon', 'Flareon', 'Meowth', 'Bidoof',
      'Wooper', 'Sprigatito', 'Fuecoco', 'Quaxly', 'Pichu', 'Raichu', 'Dragapult',
      'Blaziken', 'Absol', 'Metagross', 'Zoroark', 'Decidueye',
    ],
  },
  {
    id: 'roblox-games',
    name: 'Roblox Games',
    emoji: '🟥',
    items: [
      'Adopt Me!', 'Brookhaven RP', 'Blox Fruits', 'Pet Simulator 99', 'Doors', 'Tower of Hell',
      'Jailbreak', 'Arsenal', 'Murder Mystery 2', 'Bee Swarm Simulator', 'Natural Disaster Survival',
      'Work at a Pizza Place', 'Royale High', 'Piggy', 'Grow a Garden', 'Dress to Impress',
      'Da Hood', 'BedWars', 'Blade Ball', 'The Strongest Battlegrounds', 'Fisch',
      'Theme Park Tycoon 2', 'Welcome to Bloxburg', 'MeepCity', 'Flee the Facility',
      'Speed Run 4', 'Build a Boat for Treasure', 'Lumber Tycoon 2', 'Phantom Forces', 'Evade',
      'Rainbow Friends', '99 Nights in the Forest', 'Dead Rails', 'Anime Defenders',
      'Shindo Life', 'Pet Simulator X', 'Epic Minigames', 'Mad City', 'Rivals', 'Dig It',
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    emoji: '🍰',
    items: [
      '🍰 Cheesecake', '🎂 Birthday Cake', '🧁 Cupcake', '🍩 Donut', '🍪 Cookie', '🍫 Brownie',
      '🍦 Ice Cream', '🍧 Shaved Ice', '🥧 Apple Pie', '🍮 Flan', '🍡 Mochi', '🥮 Mooncake',
      '🍓 Strawberry Shortcake', '🍌 Banana Split', '🥐 Pain au Chocolat', '🧇 Belgian Waffle',
      '🍫 Chocolate Lava Cake', '🍋 Lemon Tart', '☕ Tiramisu', '🥥 Coconut Cream Pie',
      '🍯 Baklava', '🍭 Lollipop', '🍬 Candy', '🍿 Caramel Popcorn', '🥞 Crêpes', '🍨 Gelato',
      '🍑 Peach Cobbler', '🎃 Pumpkin Pie', 'Churros', '🍮 Crème Brûlée',
    ],
  },
  {
    id: 'superpowers',
    name: 'Superpowers',
    emoji: '🦸',
    items: [
      '🕊️ Flight', '👻 Invisibility', '⏱️ Time Travel', '🌀 Teleportation', '🧠 Telepathy',
      '💪 Super Strength', '⚡ Super Speed', '🔥 Fire Control', '❄️ Ice Control', '🌊 Water Control',
      '🌪️ Weather Control', '🩹 Healing', '♾️ Immortality', '🦎 Shapeshifting', '🔮 Seeing the Future',
      '🧲 Magnetism', '🪄 Telekinesis', '🧬 Duplication', '🐾 Talking to Animals', '🗣️ Speaking Every Language',
      '🌱 Plant Control', '🔍 X-Ray Vision', '🛡️ Invulnerability', '🌙 Never Needing Sleep',
      '📚 Instant Learning', '🍀 Perfect Luck', '🧊 Freezing Time', '🌌 Portal Creation',
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    emoji: '🏆',
    items: [
      '⚽ Soccer', '🏀 Basketball', '🏈 American Football', '⚾ Baseball', '🎾 Tennis', '🏐 Volleyball',
      '🏒 Ice Hockey', '🏉 Rugby', '🏏 Cricket', '⛳ Golf', '🏊 Swimming', '🏃 Running',
      '🚴 Cycling', '🥊 Boxing', '🤼 Wrestling', '🥋 Martial Arts', '🏓 Table Tennis', '🏸 Badminton',
      '⛷️ Skiing', '🏂 Snowboarding', '🏄 Surfing', '🛹 Skateboarding', '🧗 Rock Climbing',
      '🤸 Gymnastics', '🎳 Bowling', '🏹 Archery', '🤺 Fencing', '🏎️ Formula 1', '🥏 Ultimate Frisbee',
      '🎯 Darts',
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    emoji: '🍎',
    items: [
      '🍎 Apple', '🍐 Pear', '🍊 Orange', '🍋 Lemon', '🍌 Banana', '🍉 Watermelon', '🍇 Grapes',
      '🍓 Strawberry', '🫐 Blueberry', '🍈 Melon', '🍒 Cherry', '🍑 Peach', '🥭 Mango',
      '🍍 Pineapple', '🥥 Coconut', '🥝 Kiwi', '🍅 Tomato', '🥑 Avocado', '🫒 Olive',
      '🍏 Green Apple', 'Plum', 'Apricot', 'Pomegranate', 'Passion Fruit', '🐉 Dragon Fruit',
    ],
  },
];
